GenerateMobilityStatisticsForm.cs Added using ChessV.Games; to to fix the following 20 build failures
Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'Queen' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 50 Active
Error CS0246 The type or namespace name 'Rook' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 51 Active
Error CS0246 The type or namespace name 'Bishop' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 52 Active
Error CS0246 The type or namespace name 'Knight' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 53 Active
Error CS0246 The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 54 Active
Error CS0246 The type or namespace name 'Chancellor' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 55 Active
Error CS0246 The type or namespace name 'Archbishop' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 56 Active
Error CS0246 The type or namespace name 'Nightrider' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 57 Active
Error CS0246 The type or namespace name 'Unicorn' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 58 Active
Error CS0246 The type or namespace name 'Champion' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 59 Active
Error CS0246 The type or namespace name 'Wizard' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 60 Active
Error CS0246 The type or namespace name 'Lion' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 61 Active
Error CS0246 The type or namespace name 'WarElephant' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 62 Active
Error CS0246 The type or namespace name 'Phoenix' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 63 Active
Error CS0246 The type or namespace name 'Cleric' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 64 Active
Error CS0246 The type or namespace name 'ShortRook' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 65 Active
Error CS0246 The type or namespace name 'NarrowKnight' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 67 Active
Error CS0246 The type or namespace name 'ChargingRook' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 68 Active
Error CS0246 The type or namespace name 'ChargingKnight' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 69 Active
Error CS0246 The type or namespace name 'Colonel' could not be found (are you missing a using directive or an assembly reference?) ChessV.Utilities C:\Users\colin\Source\Repos\ChessVFork\ChessV.Utilities\Forms\GenerateMobilityStatisticsForm.cs 70 Active